- name: stop,remove web
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Amazon > stop httpd
      service: name=httpd state=stopped
      when: ansible_distribution == 'Amazon'

    - name: Amazon > remove httpd
      action: "{{ ansible_pkg_mgr }} name=httpd state=absent"
      when: ansible_distribution == 'Amazon'

    - name: ubuntu > stop nginx
      service: name=nginx state=stopped
      when: ansible_pkg_mgr == 'Ubuntu'

    - name: ubuntu > remove nginx
      apt:
        name: nginx
        purge: yes
        autoremove: yes
        state: absent
      when: ansible_distribution == "Ubuntu"
